### ISSUE TITLE
Possible way to keep disk?

### ISSUE THREAD

**Issue by dalanmiller** [joshpmcghee/parsec-terraform#3] opened 2017-04-05 14:48 UTC
I've only used Parsec once so far, but is there a way to maintain the persistent storage and therefore prevent having to redownload and log into everything? From what I understand this tool either sets up Parsec in AWS or tears it down, is that true?

**Comment by yanneves** [comment] 2017-07-17 23:40
Correct, Terraform only manages resource provisions. To keep your setup, only stop the EC2 instance using either the AWS CLI or AWS Console. You will be billed for storage even when the instance isn't running! (Approx ~~$10/mo~~ edit: $0.10/mo per GB)

**Comment by hobo05** [comment] 2018-01-22 01:58
Not sure where you got that price from. If you look here https://aws.amazon.com/ebs/pricing/. It's $0.10 per GB/mo in most regions and half that for snapshots. I forked this repo to take care maintaining persistent storage by creating a snapshot when you call destroy. It's here https://github.com/hobo05/parsec-terraform. Just forked it this weekend, so it could be a little buggy

**Comment by yanneves** [comment] 2018-01-22 18:06
Crap, thanks for pointing that out @hobo05, that should be $0.10 not $10

**Comment by tchia04** [comment] 2018-05-16 20:24
The issue is the G2 instance type has instance store for the C: drive.  Any instance with the instance store as the root drive cannot be stopped. It can only be rebooted or terminated. Once it's terminated the stuff stored in the C: drive is gone forever. 
One way to workaround this issue to to move the steam library to the D:\ drive which is an EBS volume so you don't need to login to steam and download your game all over again.  

Another caveat of using this terraform template is that the spot reservation it created is persistent.  That means even if you manually terminate the ec2 instance it will spin it back up automatically for you.  
To permanently kill the G2 instance you have to delete the spot reservation . 
I found it out the hard way the first time I used it and I had a G2 instance running over night without doing anything for 9 hours.

**Comment by yanneves** [comment] 2018-05-21 11:49
Closing in preference of #7 (thanks @tchia04!), this is a known caveat.

**Closed as completed by yanneves** 2018-05-21 11:49 UTC
